### GET index
GET {{host}}:{{port}}/
Content-Type: application/json
Accept: */*
WWW-Authenticate: {{authHeader}} {{jwt}}

### POST register
POST {{host}}:{{port}}/{{version}}/{{authRouter}}/register
Content-Type: application/json
Accept: */*
WWW-Authenticate: {{authHeader}} {{jwt}}

{
  "username": "tangzh1983",
  "password": "lipton1120",
  "confirm": "lipton1120"
}


### POST login x-www-form-urlencoded
POST {{host}}:{{port}}//login
Content-Type: application/x-www-form-urlencoded
Accept: */*

username=tangzh1983&password=lipton1120

> {%
    client.global.set("jwt", response.headers.valueOf("WWW-Authenticate").substring(7));
%}


### POST login json
POST {{host}}:{{port}}/{{version}}/{{authRouter}}/login
Content-Type: application/json
Accept: */*
WWW-Authenticate: {{authHeader}} {{jwt}}

{
  "username": "tangzh1983",
  "password": "lipton1120"
}

> {%
    client.global.set("jwt", response.headers.valueOf("WWW-Authenticate").substring(7));
%}

### POST token json
POST {{host}}:{{port}}/{{version}}/{{authRouter}}/token
Content-Type: application/json
Accept: */*
WWW-Authenticate: {{authHeader}} {{jwt}}

{
  "username": "tangzh1983",
  "password": "lipton1120"
}

### Profile
POST {{host}}:{{port}}/{{version}}/{{authRouter}}/profile
Content-Type: application/json
Accept: */*
WWW-Authenticate: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIzZGU1OTcxMi0zNGZiLTQzYzMtYWIxMC1kYWFiYjgyOWM5OTAiLCJuYmYiOjE2ODA0MjkxNTcsIjNkZTU5NzEyLTM0ZmItNDNjMy1hYjEwLWRhYWJiODI5Yzk5MCI6IiQyYSQxMCRtMmJnSUU3WEdqd3JVdzRENlpIZEZ1WDcwd1dKRGNRdXZMZnkvVTZWOVN4YzJqY3c4NTd1RyIsImlzcyI6IjNkZTU5NzEyLTM0ZmItNDNjMy1hYjEwLWRhYWJiODI5Yzk5MCIsImV4cCI6MTY4MTAzMzk1NywiaWF0IjoxNjgwNDI5MTU3LCJqdGkiOiJmZDhlMTVmYy01OTA0LTRjOTctOGVlNS02YzZjNzY4NGNjNTIifQ.wlVaHlUQIqaKia8cmXU12giPwsT1UnYq_GOZDJlR90o






