### GET index
GET {{host}}:{{port}}/
Content-Type: application/json
Accept: */*
WWW-Authenticate: {{authHeader}}{{jwt}}

### POST register
POST {{host}}:{{port}}/{{version}}/{{authRouter}}/register
Content-Type: application/json
Accept: */*
WWW-Authenticate: {{authHeader}}{{jwt}}

{
  "username": "tangzh1983",
  "password": "lipton1120",
  "confirm": "lipton1120"
}


### POST login x-www-form-urlencoded
POST {{host}}:{{port}}/login
Content-Type: application/x-www-form-urlencoded
Accept: */*
WWW-Authenticate: {{authHeader}}{{jwt}}

username=tangzh1983&password=lipton1120


### POST login json
POST {{host}}:{{port}}/login
Content-Type: application/json
Accept: */*
WWW-Authenticate: {{authHeader}}{{jwt}}

{
  "username": "tangzh1983",
  "password": "lipton1120"
}