### GET index
GET {{host}}:{{port}}/
Content-Type: application/json
Accept: */*

### POST register
POST {{host}}:{{port}}/{{version}}/{{authRouter}}/register
Content-Type: application/json
Accept: */*
WWW-Authenticate: {{authHeader}} {{jwt}}

{
  "username": "tangzh1984",
  "password": "lipton1120",
  "confirm": "lipton1120"
}


### POST login x-www-form-urlencoded
POST {{host}}:{{port}}//login
Content-Type: application/x-www-form-urlencoded
Accept: */*

username=tangzh1983&password=lipton1120

> {%
    client.global.set("jwt", response.headers.valueOf("WWW-Authenticate").substring(7));
%}


### POST login json
POST {{host}}:{{port}}/{{version}}/{{authRouter}}/login
Content-Type: application/json
Accept: */*

{
  "username": "tangzh1983",
  "password": "lipton1120"
}

> {%
    client.global.set("jwt", response.headers.valueOf("WWW-Authenticate").substring(7));
%}

### POST token json
POST {{host}}:{{port}}/{{version}}/{{authRouter}}/token
Content-Type: application/json
Accept: */*

{
  "username": "tangzh1983",
  "password": "lipton1120"
}

### Profile
POST {{host}}:{{port}}/{{version}}/{{userRouter}}/profile
Content-Type: application/json
Accept: */*
WWW-Authenticate: {{authHeader}} {{jwt}}





